### ISSUE TITLE
Download link for macOS?

### ISSUE THREAD

**Issue by UnitedWorldMedia** [JargeZ/vhs#12]
So you released a new version for this, but I couldn't download this cause it's non-existent. Could you please fix this?

**Comment by JargeZ** [comment]
Hi!
This is a pre-release, I am still in the process of creating an assembly for mac os and am experiencing some problems.

I will try to make a build by the release of the release or remove the link if it does not work out.

**Comment by JargeZ** [comment]
Now you can try macOS instruction https://github.com/JargeZ/vhs#for-mac-os-x
